# Site settings
title: Adi Saputra
description: Mahasiswa Semester 6 Jurusan Fisika Universitas Negeri Malang
url: "https://aidsuu.github.io" # URL root situs
baseurl: "" # Kosongkan untuk root situs
email: asptr00@gmail.com # Opsional, tambahkan email kamu
author: Adi Saputra

# Build settings
markdown: kramdown
plugins:
  - jekyll-email-protect

# Collections
collections:
  publications:
    output: true
  news:
    output: true
  showcase:
    output: true

# Timezone
timezone: Asia/Jakarta # Sesuaikan dengan zona waktu kamu (WIB)

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/